### ISSUE TITLE
Cannot use no args constuctor

### ISSUE THREAD

**Issue by jaudiger** [sokomishalov/lombok-rs#4]
I tried to use the no-args constructor generated by the `NoArgsConstructor` macro.

But when I tried to build the code, I got an error saying that the constructor is private:

```
error[E0624]: associated function `new_default` is private
```

It's working fine when the structure is inside the same file where I'm using the constructor, but if the structure is outside of the module where I'm using the constructor, I'm getting the error.

**Comment by sokomishalov** [comment]
Thanks for raising it!
Will be fixed in 0.3.x
